name: Discoverer
attributes:
  ORGANIZATIONNAME: LionSoftware.org
options:
  createIntermediateGroups: true
  xcodeVersion: 11.3
  groupSortPosition: top
  deploymentTarget:
    iOS: "8.0"
    macOS: "10.10"
    watchOS: "2.0"
    tvOS: "9.0"
configs:
  Debug: debug
  Release: release
fileGroups:
  - Configurations
  - Package.swift
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig
schemes:
  Discoverer_iOS:
    build:
      targets:
        Discoverer_iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [DiscovererTests_iOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  Discoverer_macOS:
    build:
      targets:
        Discoverer_macOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [DiscovererTests_macOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  Discoverer_watchOS:
    build:
      targets:
        Discoverer_watchOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: []
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  Discoverer_tvOS:
    build:
      targets:
        Discoverer_tvOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [DiscovererTests_tvOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  Discoverer:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(DISCOVERER_BUNDLE_IDENTIFIER)
        PROVISIONING_PROFILE_SPECIFIER: $(DISCOVERER_PROVISIONING_PROFILE_SPECIFIER)
    sources:
      - path: Discoverer
  DiscovererTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.discoverer.tests
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER: 
    sources:
      - path: DiscovererTests
    dependencies:
      - target: Discoverer_macOS
  Example:
    type: application
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.discoverer.example
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER:
        CURRENT_PROJECT_VERSION: 1
    sources:
      - path: Example
    dependencies:
      - target: Discoverer_macOS
    postBuildScripts:
      - script: |
                "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint
